<a href="https://colab.research.google.com/github/virlib/Coingecko-API-to-generate-Candlestick-graph-for-Bitcoin/blob/main/Web_Scraping_Using_Coingecko_API_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install pycoingecko

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pycoingecko
  Downloading pycoingecko-2.2.0-py3-none-any.whl (8.3 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from pycoingecko) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->pycoingecko) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->pycoingecko) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->pycoingecko) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->pycoingecko) (2022.6.15)
Installing collected packages: pycoingecko
Successfully installed pycoingecko-2.2.0

In [5]:
pip install mplfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting mplfinance
  Downloading mplfinance-0.12.9b1-py3-none-any.whl (70 kB)
     |████████████████████████████████| 70 kB 4.0 MB/s
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from mplfinance) (1.3.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from mplfinance) (3.2.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->mplfinance) (3.0.9)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.7/dist-packages (from matplotlib->mplfinance) (1.21.6)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->mplfinance) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->mplfinance) (1.4.3)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->mplfinance) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib->mplfinance) (4.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib->mplfinance) (1.15.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->mplfinance) (2022.1)
Installing collected packages: mplfinance
Successfully installed mplfinance-0.12.9b1

In [6]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.offline import plot
import matplotlib.pyplot as pltm
import datetime
from pycoingecko import CoinGeckoAPI
from mplfinance.original_flavor import candlestick2_ohlc

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
cg = CoinGeckoAPI()

bitcoin_data = cg.get_coin_market_chart_by_id(id='bitcoin', vs_currency='usd', days=30)

In [9]:
type(bitcoin_data )

dict

In [10]:
bitcoin_price_data = bitcoin_data['prices']

bitcoin_price_data[0:10]

[[1653588005667, 29632.43596114663],
 [1653591674475, 29633.147598648535],
 [1653595296454, 29449.983201248317],
 [1653598877103, 29505.32636894392],
 [1653602460253, 29602.45739665727],
 [1653606144180, 29545.825293413636],
 [1653609683548, 29346.781442431617],
 [1653613491783, 29211.525821933417],
 [1653616909999, 28996.307805346685],
 [1653620557521, 28974.632535857876]]

In [11]:
data = pd.DataFrame(bitcoin_price_data, columns=['TimeStamp', 'Price'])

In [12]:
data

         TimeStamp         Price
0    1653588005667  29632.435961
1    1653591674475  29633.147599
2    1653595296454  29449.983201
3    1653598877103  29505.326369
4    1653602460253  29602.457397
..             ...           ...
716  1656165614484  21190.520275
717  1656169318712  21162.119611
718  1656172816319  21062.066936
719  1656176880771  21052.234957
720  1656178305000  21118.396846

[721 rows x 2 columns]

In [13]:
data['date'] = data['TimeStamp'].apply(lambda d: datetime.date.fromtimestamp(d/1000.0))

In [14]:
data

         TimeStamp         Price        date
0    1653588005667  29632.435961  2022-05-26
1    1653591674475  29633.147599  2022-05-26
2    1653595296454  29449.983201  2022-05-26
3    1653598877103  29505.326369  2022-05-26
4    1653602460253  29602.457397  2022-05-26
..             ...           ...         ...
716  1656165614484  21190.520275  2022-06-25
717  1656169318712  21162.119611  2022-06-25
718  1656172816319  21062.066936  2022-06-25
719  1656176880771  21052.234957  2022-06-25
720  1656178305000  21118.396846  2022-06-25

[721 rows x 3 columns]

In [15]:
candlestick_data = data.groupby(data.date, as_index=False).agg({"Price": ['min', 'max', 'first', 'last']})

In [16]:
candlestick_data

          date         Price
                         min           max         first          last
0   2022-05-26  29449.983201  29633.147599  29632.435961  29545.825293
1   2022-05-27  28448.800440  29346.781442  29346.781442  28865.701315
2   2022-05-28  28626.738804  29094.581376  28646.652182  29018.734517
3   2022-05-29  28943.205149  29475.671234  29088.236453  29475.671234
4   2022-05-30  29360.436791  31735.160764  29492.503215  31720.965572
5   2022-05-31  31484.748100  32206.261554  31740.940725  31858.210768
6   2022-06-01  29676.064111  31962.818221  31813.830602  29747.614539
7   2022-06-02  29716.147919  30516.490649  29822.072290  30516.490649
8   2022-06-03  29479.742840  30607.041609  30481.013996  29730.029168
9   2022-06-04  29571.032332  29844.875625  29714.143487  29833.887022
10  2022-06-05  29658.516890  30058.723813  29872.360309  30033.187158
11  2022-06-06  29917.764052  31565.665055  29917.764052  31430.237071
12  2022-06-07  29419.159655  31522.648011  31372.584763  31522.648011
13  2022-06-08  30189.236348  31233.354220  31233.354220  30329.529040
14  2022-06-09  30012.578885  30569.690067  30229.236836  30012.578885
15  2022-06-10  29022.074454  30135.269192  30097.079849  29191.898552
16  2022-06-11  28372.280420  29376.674692  29099.974925  28668.084455
17  2022-06-12  27081.503691  28533.772908  28374.144997  27081.503691
18  2022-06-13  22638.100478  26767.269173  26767.269173  22638.100478
19  2022-06-14  21046.945034  22930.746963  22525.768350  21605.290243
20  2022-06-15  20216.090126  22479.022667  22223.152111  22479.022667
21  2022-06-16  20473.081792  22664.041895  22583.879031  20473.081792
22  2022-06-17  20322.139665  21102.458082  20408.690491  20482.871611
23  2022-06-18  17760.773382  20587.113523  20470.301152  19125.887950
24  2022-06-19  18154.041128  20710.408400  19032.396102  20710.408400
25  2022-06-20  19812.971611  20887.528591  20552.806028  20487.794933
26  2022-06-21  20463.847875  21597.009838  20636.758912  20878.311467
27  2022-06-22  19864.169914  20713.205509  20700.923933  20141.031262
28  2022-06-23  19983.566483  21006.483612  19983.566483  21006.483612
29  2022-06-24  20813.876415  21331.439173  21100.270534  21331.439173
30  2022-06-25  21052.234957  21501.718372  21262.713483  21118.396846

In [17]:
fig = go.Figure(data=[go.Candlestick(x=candlestick_data['date'],
                open=candlestick_data['Price']['first'], 
                high=candlestick_data['Price']['max'],
                low=candlestick_data['Price']['min'], 
                close=candlestick_data['Price']['last'])
                ])

fig.update_layout(xaxis_rangeslider_visible=False)

fig.show()